### ISSUE TITLE
Add generated during compilation "settings.h" file that will contain Kuzya version and build date

### ISSUE THREAD

**Issue by alexchmykhalo** [alexchmykhalo/kuzya#4]

**Comment by dmykuliak-cat** [comment]
якщо я буду створювати "settings.h" то "version.h" нам більше не потрібен?
і я не розумію як повинна генеруватися дата і версія Кузі?
генерація дати відбуваєтья кожного разу коли ми білдимо проект, чи це має бути дата релізу? так само з версією, поясни бо я не шарю)

**Comment by alexchmykhalo** [comment]
The idea is to have special header file generated and included into project, so there is no need to modify version and build date manually. If we have this Version.h file in the project, it is better to keep it (and not to create additional Settings.h file). BUT, this file should be generated by some script in our project.

That script could take one parameter (version of Kuzya). Date you could get by using some command that gives it to you. When builld server will run next Kuzya build - it will run that script, and the script will generate header. The header will be included in our project. Header will contain defines, that we will use in your code.

When developer will need to build Kuzya - he could just run that script once - to generate some header, so he will be able to compile project.

Also, please, note that this script should run on Windows and Linux\Mac, so we have few options:
 1) write 2 scripts - one for Windows, one for Linux\Mac - I think bad option, as we will duplicate code.
 2) write 1 script for Linux\Mac and run it on Windows using MSYS2 (but then developers need to have MSYS2 installed to run it)
 3) write script using Python - then it will run on both platforms

**Comment by alexchmykhalo** [comment]
Actually, in a case of option 2 - developer could run that script from Git Bash
