### ISSUE TITLE
Authors list in About Dialog

### ISSUE THREAD

**Issue by alexchmykhalo** [alexchmykhalo/kuzya#5]
* Add loading of authors list from AUTHORS file in the root of repo
 * Use scrollable text area for displaying authors in About Dialog

**Comment by OlyaOlga** [comment]
хочу використовувати scrollArea для відображення списку авторів і йому посетити лейбел(тут я хочу використовувати QString). А для загальної інформації(тої, що не буде у scrollArea) мені також QString використовувати?
